### ISSUE TITLE
Use jemalloc

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/mariadb-columnstore-vagrant#21]
See:

http://columnstore-docs.vettabase.com/doku.php?id=columnstore-getting-started:install-single-node-on-ubuntu-22.04

**Comment by rcbensley** [comment]
The repo packages already have jemalloc listed as a dependency:
`Depends: binutils, libjemalloc1 | libjemalloc2, libsnappy1v5 (>= 1.1.10), liblz4-1 (>= 0.0~r130), mariadb-server (= 1:11.3.2+maria~ubu2310), libmariadb3 (= 1:11.3.2+maria~ubu2310), net-tools, python3, libc6 (>= 2.38), libcurl4 (>= 7.16.2), libncurses6 (>= 6), libssl3 (>= 3.0.0), libstdc++6 (>= 13.1), libtinfo6 (>= 6), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4)
`

**Comment by federico-razzoli** [comment]
@rcbensley  Good, but even so, MariaDB won't use it by default. See this paragraph:

http://columnstore-docs.vettabase.com/doku.php?id=columnstore-getting-started:install-single-node-on-ubuntu-22.04#using_jemalloc

**Comment by rcbensley** [comment]
Resolved in branch

Default:

```
MariaDB [(none)]> select @@VERSION_MALLOC_LIBRARY;
+--------------------------+
| @@VERSION_MALLOC_LIBRARY |
+--------------------------+
| system                   |
+--------------------------+
1 row in set (0.000 sec)
```


With jemalloc enabled:

```
MariaDB [information_schema]> select @@VERSION_MALLOC_LIBRARY;
+------------------------------------------------------------+
| @@VERSION_MALLOC_LIBRARY                                   |
+------------------------------------------------------------+
| jemalloc 5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756 |
+------------------------------------------------------------+
1 row in set (0.001 sec)
```
