### ISSUE TITLE
redundant loop + if

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/mariadb-columnstore-vagrant#25]
https://github.com/Vettabase/mariadb-columnstore-vagrant/blame/0d60b442a09ad06062a3ea82434aba10e839ed60/install.sh#L210

I think you can remove the loop and the if and use $MDB_CLUSTER_SIZE instead of $i

**Comment by rcbensley** [comment]
This isn't needed anymore. But MDB_CLUSTER_SIZE is not iterated when creating directories on each host.
